# --- Comprehensive 10-Year Equipment Libraries ---

POPULAR_DRIVER_HEADS = [
    "Not sure / Stock Driver",
    # TaylorMade
    "TaylorMade Qi10 / Qi10 Max / Qi10 LS",
    "TaylorMade Stealth 2 / Stealth 2 Plus / Stealth 2 HD",
    "TaylorMade Stealth / Stealth Plus / Stealth HD",
    "TaylorMade SIM2 / SIM2 Max / SIM2 Max D",
    "TaylorMade SIM / SIM Max / SIM Max D",
    "TaylorMade M5 / M6 / M5 Tour",
    "TaylorMade M3 / M4",
    "TaylorMade M1 / M2 (2016 / 2017)",
    # Callaway
    "Callaway Elyte / Elyte Max",
    "Callaway Paradym Ai Smoke (MAX / D / Triple Diamond / Triple Diamond S / Fast)",
    "Callaway Paradym / Paradym X / Paradym Triple Diamond",
    "Callaway Rogue ST (MAX / MAX D / MAX LS / Triple Diamond LS)",
    "Callaway Epic MAX / Epic Speed / Epic MAX LS",
    "Callaway Mavrik / Mavrik Sub Zero / Mavrik MAX",
    "Callaway Epic Flash / Epic Flash Sub Zero",
    "Callaway Rogue / Rogue Sub Zero / Rogue Draw",
    "Callaway GBB Epic / Epic Sub Zero",
    "Callaway Big Bertha (B21 / 2023)",
    # Ping
    "Ping G440 (MAX / LST / SFT)",
    "Ping G430 MAX / 10K / LST / SFT / HL",
    "Ping G425 MAX / LST / SFT",
    "Ping G410 Plus / LST / SFT",
    "Ping G400 / G400 MAX / G400 LST / G400 SFT",
    "Ping G / G LS Tec / G SF Tec",
    # Titleist
    "Titleist GT2 / GT3 / GT4",
    "Titleist TSR2 / TSR3 / TSR4 / TSR1",
    "Titleist TSi2 / TSi3 / TSi4 / TSi1",
    "Titleist TS2 / TS3 / TS4 / TS1",
    "Titleist 917 D2 / 917 D3",
    "Titleist 915 D2 / 915 D3",
    # Cobra
    "Cobra Darkspeed (MAX / X / LS)",
    "Cobra Aerojet / Aerojet MAX / Aerojet LS",
    "Cobra LTDx / LTDx MAX / LTDx LS",
    "Cobra RadSpeed / RadSpeed XB / RadSpeed XD",
    "Cobra Speedzone / Speedzone Xtreme",
    "Cobra King F9 Speedback",
    "Cobra King F8 / F8+",
    "Cobra King F7 / F7+",
    # Mizuno
    "Mizuno ST-MAX 230 / ST-G 230",
    "Mizuno ST-Z 230 / ST-X 230 / ST-X PLTH",
    "Mizuno ST-Z 220 / ST-X 220",
    "Mizuno ST-Z / ST-X / ST200 / ST200G / ST190",
    # Srixon & Cleveland
    "Srixon ZX5 Mk II / ZX7 Mk II / ZX5 LS Mk II",
    "Srixon ZX5 / ZX7",
    "Cleveland Launcher XL / XL2 / XL Lite",
    # PXG
    "PXG 0311 Black Ops / Black Ops Tour-1",
    "PXG 0311 Gen6 (XP / XF)",
    "PXG 0311 Gen5 (XP / XF)",
    "PXG 0211",
    # Tour Edge & Wilson
    "Tour Edge Exotics E723 / C723 / E722 / C722",
    "Wilson Staff Dynapwr Carbon / Titanium",
    "Wilson Staff D9 / D7 / Cortex",
    "Other / Custom Build"
]

POPULAR_DRIVER_SHAFTS = [
    "Not sure / Standard OEM Stock Shaft",
    # Fujikura
    "Fujikura Ventus 2024 Blue / Black (VeloCore+)",
    "Fujikura Ventus Black (VeloCore 6X / 6S / 7X)",
    "Fujikura Ventus TR Black (6X / 6S / 7X)",
    "Fujikura Ventus Blue (VeloCore 5S / 6S / 6X / 7S)",
    "Fujikura Ventus TR Blue (5S / 6S / 6X)",
    "Fujikura Ventus Red (VeloCore 5R / 5S / 6S)",
    "Fujikura Ventus TR Red (5R / 5S / 6S)",
    "Fujikura Speeder NX Green / Blue / Black",
    "Fujikura Motore X F1 / F3",
    "Fujikura Air Speeder (35g / 40g / 45g)",
    # Mitsubishi Chemical (MCA)
    "Mitsubishi Tensei Pro 1K Black (65S / 65X / 75X)",
    "Mitsubishi Tensei Pro 1K White (60S / 60X / 70X)",
    "Mitsubishi Tensei Pro 1K Blue / Orange (60S / 60X)",
    "Mitsubishi Tensei AV Raw White (65S / 75X)",
    "Mitsubishi Tensei AV Raw Blue (55S / 65S / 65R)",
    "Mitsubishi Tensei AV Raw Orange (65S / 75X)",
    "Mitsubishi Kai'li White (60S / 60X / 70X)",
    "Mitsubishi Kai'li Blue (60S / 60R / 70S)",
    "Mitsubishi Kai'li Red (50R / 60S)",
    "Mitsubishi Diamana GT / TB / ZF / PD / DF",
    "Mitsubishi Grand Bassara (29g / 39g / 49g)",
    "Mitsubishi Vanquish (4R / 5S / 5X)",
    # Project X / True Temper
    "Project X HZRDUS Smoke Black RDX (6.0 / 6.5)",
    "Project X HZRDUS Smoke Blue RDX (Counterbalanced)",
    "Project X HZRDUS Smoke Red RDX (Active Tip)",
    "Project X HZRDUS Black / Yellow / Red (Gen 4 / Hand Crafted)",
    "Project X EvenFlow Riptide / Riptide CB (50g / 60g / 70g)",
    "Project X Cypher / Cypher 2.0 (40g / 50g 5.0 / 5.5)",
    # Graphite Design (Tour AD)
    "Graphite Design Tour AD VF (6S / 6X / 7X)",
    "Graphite Design Tour AD CQ (5S / 6S / 6X)",
    "Graphite Design Tour AD UB (6S / 6X / 7S)",
    "Graphite Design Tour AD XC (6S / 6X)",
    "Graphite Design Tour AD DI (5S / 6S / 6X / 7S - Orange)",
    "Graphite Design Tour AD IZ (5S / 6S / 6X)",
    "Graphite Design Tour AD TP / VR / GP",
    # UST Mamiya
    "UST Mamiya LIN-Q M40X White (6F4 / 6F5 / 7F5)",
    "UST Mamiya LIN-Q M40X Blue / Red (6F4 / 6F5)",
    "UST Mamiya Helium Nanocore (4F2 / 5F3 / 5F4)",
    "UST Mamiya Proforce V2 / V2 Black (55 / 65 / 75)",
    "UST Mamiya Attas (King / DAAAS / CoooL)",
    # Aldila & KBS
    "Aldila Ascent PL / Red (40g / 50g)",
    "Aldila Rogue Silver 110 MSI (60S / 70X)",
    "Aldila Rogue White 130 MSI (60S / 70X)",
    "Aldila NV / NVS Green/Pink (2KXV)",
    "KBS TD Graphite (Cat 2 / Cat 3 / Cat 4 / Cat 5)",
    # OEM Proprietary Stock
    "Ping Tour 2.0 Chrome 65 (R / S / X)",
    "Ping Tour 2.0 Black 65 / 75 (S / X)",
    "Ping Alta CB 55 Black / Red / Slate",
    "Callaway MCA Tensei AV Blue (Stock 55g)",
    "TaylorMade Fujikura Speeder TM50",
    "Titleist MCA Tensei 1K Black (Stock)",
    "Cobra MCA Lin-Q White (Stock)",
    "Other / Custom Shaft"
]

POPULAR_IRON_HEADS = [
    "Not sure / Stock Set",
    # TaylorMade
    "TaylorMade P790 (2023 / 2021 / 2019 / 2017)",
    "TaylorMade P770 (2024 / 2023 / 2020)",
    "TaylorMade P7CB / P7MB / P7MC",
    "TaylorMade Qi Irons / Qi HL",
    "TaylorMade Stealth HD / Stealth",
    "TaylorMade SIM2 Max / SIM2 Max OS",
    "TaylorMade SIM Max / SIM Max OS",
    "TaylorMade M6 / M5 / M4 / M2 / M1",
    # Callaway
    "Callaway Apex Ai200 / Apex Ai300 / Apex Ti Fusion",
    "Callaway Apex 24 (CB / MB / Pro)",
    "Callaway Apex 21 (Standard / Pro / DCB)",
    "Callaway Apex 19 / Apex Pro 19",
    "Callaway Apex CF16 / Apex Pro 16",
    "Callaway Paradym / Paradym X",
    "Callaway Paradym Ai Smoke / Ai Smoke HL / MAX Fast",
    "Callaway Rogue ST (MAX / MAX OS / Pro)",
    "Callaway Mavrik / Mavrik Pro / Mavrik MAX",
    "Callaway Steelhead XR / Big Bertha (21 / 23)",
    # Ping
    "Ping Blueprint S / Blueprint T",
    "Ping i230 / i210 / i200 / iBlade",
    "Ping i530 / i525 / i500",
    "Ping G430 / G430 HL",
    "Ping G425",
    "Ping G410 / G400 / G710 / G700",
    "Ping i59",
    # Titleist
    "Titleist T100 (2023 / 2021 / 2019)",
    "Titleist T150 (2023)",
    "Titleist T200 (2023 / 2021 / 2019)",
    "Titleist T350 (2023) / T300 (2021 / 2019)",
    "Titleist T400 (Super Game Improvement)",
    "Titleist 620 CB / 620 MB",
    "Titleist 718 AP2 / AP3 / AP1",
    "Titleist 716 AP2 / AP1 / CB / MB",
    # Cobra (Variable & ONE Length)
    "Cobra King Forged Tec (2023 / 2020 Standard)",
    "Cobra King Forged Tec ONE Length",
    "Cobra King Tour / King CB / King MB",
    "Cobra Darkspeed / Darkspeed ONE Length",
    "Cobra Aerojet / Aerojet ONE Length",
    "Cobra LTDx / LTDx ONE Length",
    "Cobra RadSpeed / RadSpeed ONE Length",
    "Cobra Speedzone / Speedzone ONE Length",
    "Cobra King F9 / F8 / F7 (Standard & ONE Length)",
    # Mizuno
    "Mizuno Pro 241 / 243 / 245 / Fli-Hi",
    "Mizuno Pro 221 / 223 / 225",
    "Mizuno JPX 923 (Hot Metal / HM Pro / HM HL / Forged / Tour)",
    "Mizuno JPX 921 (Hot Metal / HM Pro / Forged / Tour)",
    "Mizuno JPX 919 (Hot Metal / HM Pro / Forged / Tour)",
    "Mizuno MP-20 (MMC / HMB / MB)",
    # Srixon & Cleveland
    "Srixon ZX7 Mk II / ZX5 Mk II / ZX4 Mk II",
    "Srixon ZX7 / ZX5 / ZX4",
    "Srixon Z-Forged II",
    "Cleveland Launcher XL / XL Halo / Halo XL Full-Face",
    # PXG
    "PXG 0311 Gen7 (P / XP)",
    "PXG 0311 Gen6 (P / XP / T)",
    "PXG 0311 Gen5 (P / XP / T)",
    "PXG 0211 XCOR2 / 0211 DC",
    # Wilson Staff & Tour Edge
    "Wilson Staff Dynapwr Forged / Cast",
    "Wilson Staff D9 / D9 Forged / D7",
    "Wilson Staff FG Tour V6 / Staff Model CB / Blade",
    "Tour Edge Exotics E723 / C723 / E722 / C722",
    "Other / Custom Set"
]

POPULAR_IRON_SHAFTS = [
    "Not sure / Stock Steel",
    # True Temper (Steel)
    "True Temper Dynamic Gold (S300 / X100 / R300 - Standard 130g)",
    "True Temper Dynamic Gold 120 (S300 / X100)",
    "True Temper Dynamic Gold 105 (R300 / S300 / X100)",
    "True Temper Dynamic Gold 95 (R300 / S300)",
    "True Temper Dynamic Gold Mid 100 / 115",
    "True Temper Elevate MPH 95 (R / S)",
    "True Temper Elevate 95 / 105 / Tour",
    "True Temper XP 95 / XP 105 / XP 115",
    # Project X (Steel)
    "Project X LZ (5.0 / 5.5 / 6.0 / 6.5 - 110g to 125g)",
    "Project X IO (5.5 / 6.0 / 6.5)",
    "Project X Rifle Steel (5.0 / 5.5 / 6.0 / 6.5 / 7.0)",
    # KBS (Steel)
    "KBS $-Taper (110R / 115S / 120S+ / 125X)",
    "KBS $-Taper Lite (95R / 100S / 105X)",
    "KBS Tour (110R / 120S / 130X)",
    "KBS Tour 90 (Regular / Stiff)",
    "KBS Tour 105 (Regular / Stiff / X)",
    "KBS Tour V (100R / 110S / 120X)",
    "KBS C-Taper (110R / 120S / 125S+ / 130X)",
    "KBS C-Taper Lite (105R / 110S / 115X)",
    "KBS Max 80 (Lightweight Active High Launch)",
    # Nippon (Steel)
    "Nippon N.S. Pro Modus3 Tour 105 (R / S / X)",
    "Nippon N.S. Pro Modus3 Tour 115 (10th Anniv / R / S / X)",
    "Nippon N.S. Pro Modus3 Tour 120 (R / S / X)",
    "Nippon N.S. Pro Modus3 Tour 125 / 130",
    "Nippon N.S. Pro 950GH neo (R / S)",
    "Nippon N.S. Pro 950GH / 850GH / 750GH",
    "Nippon Zelos 6 / Zelos 7 / Zelos 8 (Ultra-Light Alloy)",
    # Tour Composite & Heavy Graphite
    "Aerotech SteelFiber i95 (Regular / Stiff)",
    "Aerotech SteelFiber i110 (Stiff / X-Stiff)",
    "Aerotech SteelFiber i70 / i80 (Senior / Regular)",
    "Aerotech SteelFiber fc90 / fc115 (Flighted)",
    "Mitsubishi Chemical MMT 85 (Regular / Stiff)",
    "Mitsubishi Chemical MMT 95 (Stiff / X-Stiff)",
    "Mitsubishi Chemical MMT 105 / 125 (Tour Stiff/TX)",
    "Mitsubishi Chemical MMT 65 / 75 (Senior / Regular)",
    "UST Mamiya Recoil Dart 90 / 105 (F3-Reg / F4-Stiff / F5-X)",
    "UST Mamiya Recoil Dart 65 / 75 (F2-Lite / F3-Reg)",
    "UST Mamiya Recoil 95 / 110 (F3 / F4 / F5)",
    "UST Mamiya Recoil ESX 460 / 470 (Active Lightweight)",
    "Fujikura Axiom 75 / 105 / 125 (VeloCore Composite)",
    "KBS TGI Tour Graphite (60 / 70 / 80 / 90 / 100)",
    "KBS MAX Graphite (45 / 55 / 65)",
    "Ping AWT 2.0 (Ascending Weight Steel)",
    "Callaway True Temper Speed Step 80",
    "TaylorMade KBS Max 85",
    "Other / Lightweight Stock Graphite"
]
